version: 0.0
os: linux
files:
- source: application
  destination: /opt/goapp
- source: public/index.html
  destination: /opt/goapp/public
hooks:
  ApplicationStart:
  - location: scripts/start_server
    timeout: 300
    runas: root
