version: 0.0
os: linux
files:
- source: GoApp.zip
  destination: /opt/goapp
- source: public/index.html
  destination: /opt/goapp/public/index.html
hooks:
  ApplicationStart:
  - location: scrips/start_server
    timeout: 300
    runas: root
