version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
    - go build -o application
  post_build:
    commands:
    - zip GoApp.zip application appspec.yml public/index.html
artifacts:
  files:
  - appspec.yml
  - application
  - public/index.html
  discard-paths: no
