version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
    - go build -o application
  post_build:
    commands:
    - zip GoApp.zip application public/index.html
  artifacts:
    files:
    - GoApp.zip
