version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
    - go build -o application
artifacts:
  files:
  - appspec.yml
  - application
  - public/index.html
  - scripts/start_server
  name: GoApp-$(date +'%s')
  discard-paths: no
